Log from port forwarding:

vagrant@developervm:/vagrant-shared/DevOps_Microservices$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "udacity-mlm" already exists
NAME          READY   STATUS    RESTARTS   AGE
udacity-mlm   1/1     Running   0          83s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000


Log from the pod:

vagrant@developervm:~$ kubectl logs udacity-mlm
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.17.0.5:80
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 744-154-076
[2022-10-14 16:23:09,034] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-10-14 16:23:09,047] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-10-14 16:23:09,057] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-10-14 16:23:09,061] INFO in app: Prediction: [20.35373177134412]
127.0.0.1 - - [14/Oct/2022 16:23:09] "POST /predict HTTP/1.1" 200 -